services:
  redis:
    image: redis
    ports:
      - "6390:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8090:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379