services:
  redis:
    image: redis
    ports:
      - "6390:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8090:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - REDIS_ROUTER=redis://redis:6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    depends_on:
      - redis
      - mysql
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info
    environment:
      - REDIS_ROUTER=redis://redis:6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    depends_on:
      - redis
      - mysql
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app beat --loglevel=info
    environment:
      - REDIS_ROUTER=redis://redis:6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    depends_on:
      - redis
      - mysql
      - worker
  mysql:
    image: mysql:8.0
    ports:
      - "3390:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: collector_db
      MYSQL_USER: smitpeter777
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  mysql_data:
